# fly.toml app configuration file generated for timesheet-eng on 2023-06-27T21:31:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "timesheet-eng"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
